In [2]:
import numpy as np
list1=[12,15,17,23,45]
numpy_list=np.array(list1)
print(numpy_list)

[12 15 17 23 45]


In [5]:
arra_a=np.array([[4,7,8],[3,5,9],[4,5,8]])
arra_a

array([[4, 7, 8],
       [3, 5, 9],
       [4, 5, 8]])

In [6]:
arra2=np.ones_like(arra_a)
print(arra2)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [7]:
aray_pi=np.full((3,4),fill_value=3.14)
print(aray_pi)

[[3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]]


In [8]:
arr=np.full((5,3),fill_value=2.5)
print(arr)

[[2.5 2.5 2.5]
 [2.5 2.5 2.5]
 [2.5 2.5 2.5]
 [2.5 2.5 2.5]
 [2.5 2.5 2.5]]


In [9]:
alist_array=np.asarray([23,45,67,42,78],dtype="float64")
print(alist_array)

[23. 45. 67. 42. 78.]


In [11]:
in_new=np.linspace(10,30,9)
print(in_new)

[10.  12.5 15.  17.5 20.  22.5 25.  27.5 30. ]


In [13]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [14]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.diag([5,9,7])

array([[5, 0, 0],
       [0, 9, 0],
       [0, 0, 7]])

In [17]:
arr.ndim

2

In [18]:
print(numpy_list)

[12 15 17 23 45]


In [37]:
print(numpy_list[1:])

[15 17 23 45]


In [38]:
print(arr)

[[2.5 2.5 2.5]
 [2.5 2.5 2.5]
 [2.5 2.5 2.5]
 [2.5 2.5 2.5]
 [2.5 2.5 2.5]]


In [40]:
print(arr[0:2,0:3])

[[2.5 2.5 2.5]
 [2.5 2.5 2.5]]
