In [9]:
import numpy as np
lis_marks=[40,67,89,45,67]
numpy_lis=np.array(lis_marks)
print(numpy_lis.dtype)

int64


In [14]:
print(np.zeros((3,3),dtype="int32"))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [15]:
print(np.zeros((7,10),dtype="float64"))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [16]:
arra_a=np.array([[1,2,3],[5,6,7],[8,9,10]])
print(arra_a)

[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]]


In [18]:
array_like=np.zeros_like(arra_a)
print(array_like)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [21]:
print(np.ones((4,4),dtype="int32"))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [22]:
arra_1=np.array([[12,15,19],[23,45,22],[56,73,57]])
print(arra_1)

[[12 15 19]
 [23 45 22]
 [56 73 57]]


In [24]:
arra_2=np.ones_like(arra_1)
print(arra_2)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
