In [1]:
import numpy as np
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
aray_pi=np.full((2,3),fill_value=7)
print(aray_pi)

[[7 7 7]
 [7 7 7]]


In [12]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:7])

[5 6 7]


In [16]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,19]])
print(arr[0:2,4])

[ 5 19]


In [19]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1])

[4 5 6]


In [26]:
arrj=np.arange(0,12).reshape(3,4)
print(arrj)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
