In [ ]:
import numpy as np
arra=np.ones((2,3))
print(arra)

In [2]:
print(arra.shape)

(2, 3)


In [3]:
print(arra.size)

6


In [5]:
arrb=np.array([[12,34,56,78,90],[45,67,89,98,7]])
print(arrb)

[[12 34 56 78 90]
 [45 67 89 98  7]]


In [8]:
np.size(arrb)

10

In [12]:
arrc=arrb.reshape((5,2))
print(arrc)

[[12 34]
 [56 78]
 [90 45]
 [67 89]
 [98  7]]


In [16]:
arrd=np.arange(30)
print(arrd)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [17]:
arrf=arrd.reshape(6,5)
print(arrf)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [25]:
arrj=np.arange(0,10).reshape(2,5)
arrk=np.arange(10,20).reshape(2,5)
print(arrj+arrk)

[[10 12 14 16 18]
 [20 22 24 26 28]]


In [20]:
arrj=np.arange(0,10).reshape(2,5)
print(arrj)

[[0 1 2 3 4]
 [5 6 7 8 9]]
