In [12]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:9:2])

[2 4 6 8]


In [26]:
aray2d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(aray2d[0:2,0:3])

[[1 2 3]
 [6 7 8]]


In [32]:
arra=np.ones((2,3))
print(arra)

[[1. 1. 1.]
 [1. 1. 1.]]


In [33]:
print(arra.ndim)

2


In [34]:
print(arr.ndim)

1
